name: 'test_project'

config-version: 2
version: '0.1'

profile: 'test_project'

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  test_project:
      materialized: table
      staging:
        materialized: table
